#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos.AccesoDatosLinq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DemoGamesHub36")]
	public partial class ConexionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public ConexionDataContext() : 
				base(global::AccesoDatos.Properties.Settings.Default.DemoGamesHub36ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ConexionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CERRAR_SESION_CON_TOKEN")]
		public int SP_CERRAR_SESION_CON_TOKEN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOKEN_SESION", DbType="NVarChar(255)")] string tOKEN_SESION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tOKEN_SESION, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CREAR_USUARIO")]
		public int SP_CREAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_USUARIO", DbType="NVarChar(50)")] string nOMBRE_USUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EMAIL", DbType="NVarChar(50)")] string eMAIL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTRASENA", DbType="NVarChar(500)")] string cONTRASENA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE_USUARIO, eMAIL, cONTRASENA, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ENVIAR_SOLICITUD_AMISTAD")]
		public int SP_ENVIAR_SOLICITUD_AMISTAD([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOKEN_SESION", DbType="NVarChar(255)")] string tOKEN_SESION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UID_AMIGO", DbType="Char(9)")] string uID_AMIGO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tOKEN_SESION, uID_AMIGO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INICIAR_SESION")]
		public int SP_INICIAR_SESION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EMAIL", DbType="NVarChar(50)")] string eMAIL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTRASENA", DbType="NVarChar(500)")] string cONTRASENA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ORIGEN", DbType="NVarChar(MAX)")] string oRIGEN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOKEN_GENERADO", DbType="NVarChar(255)")] ref string tOKEN_GENERADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), eMAIL, cONTRASENA, oRIGEN, iDRETURN, tOKEN_GENERADO, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			tOKEN_GENERADO = ((string)(result.GetParameterValue(4)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_AMIGOS")]
		public ISingleResult<SP_OBTENER_AMIGOSResult> SP_OBTENER_AMIGOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOKEN_SESION", DbType="NVarChar(255)")] string tOKEN_SESION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tOKEN_SESION);
			return ((ISingleResult<SP_OBTENER_AMIGOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_COMPRAS_USUARIO")]
		public ISingleResult<SP_OBTENER_COMPRAS_USUARIOResult> SP_OBTENER_COMPRAS_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOKEN_SESION", DbType="NVarChar(255)")] string tOKEN_SESION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tOKEN_SESION);
			return ((ISingleResult<SP_OBTENER_COMPRAS_USUARIOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_ESTADO_SOLICITUD_AMISTAD")]
		public ISingleResult<SP_OBTENER_ESTADO_SOLICITUD_AMISTADResult> SP_OBTENER_ESTADO_SOLICITUD_AMISTAD([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOKEN_SESION", DbType="NVarChar(255)")] string tOKEN_SESION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SOLICITUD_ID", DbType="Int")] System.Nullable<int> sOLICITUD_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tOKEN_SESION, sOLICITUD_ID);
			return ((ISingleResult<SP_OBTENER_ESTADO_SOLICITUD_AMISTADResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_ITEMS_TIENDA")]
		public ISingleResult<SP_OBTENER_ITEMS_TIENDAResult> SP_OBTENER_ITEMS_TIENDA()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_OBTENER_ITEMS_TIENDAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_JUEGOS")]
		public ISingleResult<SP_OBTENER_JUEGOSResult> SP_OBTENER_JUEGOS()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_OBTENER_JUEGOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_LOGROS_BLOQUEADOS")]
		public ISingleResult<SP_OBTENER_LOGROS_BLOQUEADOSResult> SP_OBTENER_LOGROS_BLOQUEADOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOKEN_SESION", DbType="NVarChar(255)")] string tOKEN_SESION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tOKEN_SESION);
			return ((ISingleResult<SP_OBTENER_LOGROS_BLOQUEADOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_LOGROS_DESBLOQUEADOS")]
		public ISingleResult<SP_OBTENER_LOGROS_DESBLOQUEADOSResult> SP_OBTENER_LOGROS_DESBLOQUEADOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOKEN_SESION", DbType="NVarChar(255)")] string tOKEN_SESION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tOKEN_SESION);
			return ((ISingleResult<SP_OBTENER_LOGROS_DESBLOQUEADOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_NOTIFICACIONES_USUARIO")]
		public ISingleResult<SP_OBTENER_NOTIFICACIONES_USUARIOResult> SP_OBTENER_NOTIFICACIONES_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOKEN_SESION", DbType="NVarChar(255)")] string tOKEN_SESION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tOKEN_SESION);
			return ((ISingleResult<SP_OBTENER_NOTIFICACIONES_USUARIOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_PUNTAJE_TOTAL_USUARIOS")]
		public ISingleResult<SP_OBTENER_PUNTAJE_TOTAL_USUARIOSResult> SP_OBTENER_PUNTAJE_TOTAL_USUARIOS()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_OBTENER_PUNTAJE_TOTAL_USUARIOSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_SANCIONES")]
		public ISingleResult<SP_OBTENER_SANCIONESResult> SP_OBTENER_SANCIONES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOKEN_SESION", DbType="NVarChar(255)")] string tOKEN_SESION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tOKEN_SESION);
			return ((ISingleResult<SP_OBTENER_SANCIONESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_SOLICITUDES_AMISTAD_PENDIENTES")]
		public ISingleResult<SP_OBTENER_SOLICITUDES_AMISTAD_PENDIENTESResult> SP_OBTENER_SOLICITUDES_AMISTAD_PENDIENTES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOKEN_SESION", DbType="NVarChar(255)")] string tOKEN_SESION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tOKEN_SESION);
			return ((ISingleResult<SP_OBTENER_SOLICITUDES_AMISTAD_PENDIENTESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OBTENER_TODOS_LOS_REPORTES")]
		public ISingleResult<SP_OBTENER_TODOS_LOS_REPORTESResult> SP_OBTENER_TODOS_LOS_REPORTES()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_OBTENER_TODOS_LOS_REPORTESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CERRAR_JUEGO_INDIVIDUAL_POR_TOKEN")]
		public int SP_CERRAR_JUEGO_INDIVIDUAL_POR_TOKEN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PARTIDA_ID", DbType="Int")] System.Nullable<int> pARTIDA_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOKEN_SESION", DbType="NVarChar(255)")] string tOKEN_SESION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PUNTAJE_OBTENIDO", DbType="Int")] System.Nullable<int> pUNTAJE_OBTENIDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pARTIDA_ID, tOKEN_SESION, pUNTAJE_OBTENIDO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ACEPTAR_SOLICITUD_AMISTAD")]
		public int SP_ACEPTAR_SOLICITUD_AMISTAD([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SOLICITUD_ID", DbType="Int")] System.Nullable<int> sOLICITUD_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOKEN_SESION", DbType="NVarChar(255)")] string tOKEN_SESION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sOLICITUD_ID, tOKEN_SESION, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CERRAR_PARTIDA_MULTIJUGADOR_CSV")]
		public int SP_CERRAR_PARTIDA_MULTIJUGADOR_CSV([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PARTIDA_ID", DbType="Int")] System.Nullable<int> pARTIDA_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PUNTAJES_CSV", DbType="NVarChar(MAX)")] string pUNTAJES_CSV, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pARTIDA_ID, pUNTAJES_CSV, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_COMPRAR_ITEM_TIENDA")]
		public int SP_COMPRAR_ITEM_TIENDA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOKEN_SESION", DbType="NVarChar(255)")] string tOKEN_SESION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OBJETO_ID", DbType="Int")] System.Nullable<int> oBJETO_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tOKEN_SESION, oBJETO_ID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_DESBLOQUEAR_LOGRO_POR_TOKEN")]
		public int SP_DESBLOQUEAR_LOGRO_POR_TOKEN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOKEN_SESION", DbType="NVarChar(255)")] string tOKEN_SESION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LOGRO_ID", DbType="Int")] System.Nullable<int> lOGRO_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CRITERIO_VALOR", DbType="Int")] System.Nullable<int> cRITERIO_VALOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tOKEN_SESION, lOGRO_ID, cRITERIO_VALOR, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EDITAR_USUARIO2")]
		public int SP_EDITAR_USUARIO2([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOKEN_SESION", DbType="NVarChar(255)")] string tOKEN_SESION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUEVO_NOMBRE", DbType="NVarChar(50)")] string nUEVO_NOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUEVO_EMAIL", DbType="NVarChar(50)")] string nUEVO_EMAIL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tOKEN_SESION, nUEVO_NOMBRE, nUEVO_EMAIL, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ELIMINAR_AMIGO")]
		public int SP_ELIMINAR_AMIGO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOKEN_SESION", DbType="NVarChar(255)")] string tOKEN_SESION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AMIGO_UID", DbType="Char(9)")] string aMIGO_UID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tOKEN_SESION, aMIGO_UID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ENVIAR_MENSAJE")]
		public int SP_ENVIAR_MENSAJE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOKEN_EMISOR", DbType="NVarChar(255)")] string tOKEN_EMISOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RECEPTOR_UID", DbType="Char(9)")] string rECEPTOR_UID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MENSAJE_TEXTO", DbType="NVarChar(500)")] string mENSAJE_TEXTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tOKEN_EMISOR, rECEPTOR_UID, mENSAJE_TEXTO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_GUARDAR_PARTIDA_IA")]
		public int SP_GUARDAR_PARTIDA_IA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOKEN_SESION", DbType="NVarChar(255)")] string tOKEN_SESION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="JUEGO_ID", DbType="Int")] System.Nullable<int> jUEGO_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="INSTRUCCIONES_INICIALES", DbType="NVarChar(MAX)")] string iNSTRUCCIONES_INICIALES, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTEXTO_JUEGO", DbType="NVarChar(MAX)")] string cONTEXTO_JUEGO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NARRATIVA_FONDO", DbType="NVarChar(MAX)")] string nARRATIVA_FONDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ESTADO_MENTAL", DbType="NVarChar(100)")] string eSTADO_MENTAL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONFIGURACION", DbType="NVarChar(MAX)")] string cONFIGURACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PARTIDA_ID", DbType="Int")] ref System.Nullable<int> pARTIDA_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PARTIDA_UID", DbType="Int")] ref System.Nullable<int> pARTIDA_UID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tOKEN_SESION, jUEGO_ID, iNSTRUCCIONES_INICIALES, cONTEXTO_JUEGO, nARRATIVA_FONDO, eSTADO_MENTAL, cONFIGURACION, pARTIDA_ID, pARTIDA_UID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			pARTIDA_ID = ((System.Nullable<int>)(result.GetParameterValue(7)));
			pARTIDA_UID = ((System.Nullable<int>)(result.GetParameterValue(8)));
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(9)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(10)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(11)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_GUARDAR_PARTIDA_INDIVIDUAL")]
		public int SP_GUARDAR_PARTIDA_INDIVIDUAL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOKEN_SESION", DbType="NVarChar(255)")] string tOKEN_SESION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="JUEGO_ID", DbType="Int")] System.Nullable<int> jUEGO_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PARTIDA_ID", DbType="Int")] ref System.Nullable<int> pARTIDA_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PARTIDA_UID", DbType="Int")] ref System.Nullable<int> pARTIDA_UID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tOKEN_SESION, jUEGO_ID, pARTIDA_ID, pARTIDA_UID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			pARTIDA_ID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			pARTIDA_UID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_ITEM_TIENDA")]
		public int SP_INGRESAR_ITEM_TIENDA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_OBJETO", DbType="NVarChar(100)")] string nOMBRE_OBJETO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRECIO_PUNTOS", DbType="Int")] System.Nullable<int> pRECIO_PUNTOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="NVarChar(255)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE_OBJETO, pRECIO_PUNTOS, dESCRIPCION, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_JUEGO")]
		public int SP_INGRESAR_JUEGO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_JUEGO", DbType="NVarChar(100)")] string nOMBRE_JUEGO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO_JUEGO", DbType="NVarChar(20)")] string tIPO_JUEGO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="JUEGO_ID", DbType="Int")] ref System.Nullable<int> jUEGO_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE_JUEGO, tIPO_JUEGO, jUEGO_ID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			jUEGO_ID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INGRESAR_LOGRO")]
		public int SP_INGRESAR_LOGRO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_LOGRO", DbType="NVarChar(100)")] string nOMBRE_LOGRO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="NVarChar(255)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="JUEGO_ID", DbType="Int")] System.Nullable<int> jUEGO_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PUNTOS_OTORGADOS", DbType="Int")] System.Nullable<int> pUNTOS_OTORGADOS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CRITERIO_DESBLOQUEO", DbType="NVarChar(50)")] string cRITERIO_DESBLOQUEO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VALOR_CRITERIO", DbType="Int")] System.Nullable<int> vALOR_CRITERIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USUARIO_ADMIN_ID", DbType="Int")] System.Nullable<int> uSUARIO_ADMIN_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE_LOGRO, dESCRIPCION, jUEGO_ID, pUNTOS_OTORGADOS, cRITERIO_DESBLOQUEO, vALOR_CRITERIO, uSUARIO_ADMIN_ID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(7)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(8)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(9)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INICIAR_PARTIDA_MULTIJUGADOR")]
		public int SP_INICIAR_PARTIDA_MULTIJUGADOR([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOKEN_SESION", DbType="NVarChar(255)")] string tOKEN_SESION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="JUEGO_ID", DbType="Int")] System.Nullable<int> jUEGO_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PARTIDA_ID", DbType="Int")] ref System.Nullable<int> pARTIDA_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PARTIDA_UID", DbType="Int")] ref System.Nullable<int> pARTIDA_UID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tOKEN_SESION, jUEGO_ID, pARTIDA_ID, pARTIDA_UID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			pARTIDA_ID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			pARTIDA_UID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_MARCAR_MENSAJES_LEIDOS")]
		public int SP_MARCAR_MENSAJES_LEIDOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOKEN_SESION", DbType="NVarChar(255)")] string tOKEN_SESION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AMIGO_UID", DbType="Char(9)")] string aMIGO_UID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tOKEN_SESION, aMIGO_UID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RECHAZAR_SOLICITUD_AMISTAD")]
		public int SP_RECHAZAR_SOLICITUD_AMISTAD([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOKEN_SESION", DbType="NVarChar(255)")] string tOKEN_SESION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SOLICITUD_ID", DbType="Int")] System.Nullable<int> sOLICITUD_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tOKEN_SESION, sOLICITUD_ID, iDRETURN);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_RECUPERAR_MENSAJES")]
		public ISingleResult<SP_RECUPERAR_MENSAJESResult> SP_RECUPERAR_MENSAJES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOKEN_SESION", DbType="NVarChar(255)")] string tOKEN_SESION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AMIGO_UID", DbType="Char(9)")] string aMIGO_UID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tOKEN_SESION, aMIGO_UID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((ISingleResult<SP_RECUPERAR_MENSAJESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_REPORTAR_USUARIO")]
		public int SP_REPORTAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOKEN_SESION", DbType="NVarChar(255)")] string tOKEN_SESION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="REPORTADO_UID", DbType="Char(9)")] string rEPORTADO_UID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="NVarChar(500)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tOKEN_SESION, rEPORTADO_UID, dESCRIPCION, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_UNIRSE_PARTIDA_MULTIJUGADOR_UID")]
		public int SP_UNIRSE_PARTIDA_MULTIJUGADOR_UID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TOKEN_SESION", DbType="NVarChar(255)")] string tOKEN_SESION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PARTIDA_UID", DbType="Int")] System.Nullable<int> pARTIDA_UID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tOKEN_SESION, pARTIDA_UID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_SANCIONAR_USUARIO_REPORTADO")]
		public int SP_SANCIONAR_USUARIO_REPORTADO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="REPORTE_ID", DbType="Int")] System.Nullable<int> rEPORTE_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO_SANCION", DbType="NVarChar(20)")] string tIPO_SANCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="NVarChar(500)")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_FIN", DbType="DateTime")] System.Nullable<System.DateTime> fECHA_FIN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rEPORTE_ID, tIPO_SANCION, dESCRIPCION, fECHA_FIN, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class SP_OBTENER_AMIGOSResult
	{
		
		private int _AMIGO_ID;
		
		private string _NOMBRE_USUARIO;
		
		private string _EMAIL;
		
		private System.DateTime _FECHA_AMISTAD;
		
		public SP_OBTENER_AMIGOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMIGO_ID", DbType="Int NOT NULL")]
		public int AMIGO_ID
		{
			get
			{
				return this._AMIGO_ID;
			}
			set
			{
				if ((this._AMIGO_ID != value))
				{
					this._AMIGO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_USUARIO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE_USUARIO
		{
			get
			{
				return this._NOMBRE_USUARIO;
			}
			set
			{
				if ((this._NOMBRE_USUARIO != value))
				{
					this._NOMBRE_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_AMISTAD", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_AMISTAD
		{
			get
			{
				return this._FECHA_AMISTAD;
			}
			set
			{
				if ((this._FECHA_AMISTAD != value))
				{
					this._FECHA_AMISTAD = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_COMPRAS_USUARIOResult
	{
		
		private int _COMPRA_ID;
		
		private string _NOMBRE_OBJETO;
		
		private System.DateTime _FECHA_COMPRA;
		
		public SP_OBTENER_COMPRAS_USUARIOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPRA_ID", DbType="Int NOT NULL")]
		public int COMPRA_ID
		{
			get
			{
				return this._COMPRA_ID;
			}
			set
			{
				if ((this._COMPRA_ID != value))
				{
					this._COMPRA_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_OBJETO", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NOMBRE_OBJETO
		{
			get
			{
				return this._NOMBRE_OBJETO;
			}
			set
			{
				if ((this._NOMBRE_OBJETO != value))
				{
					this._NOMBRE_OBJETO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_COMPRA", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_COMPRA
		{
			get
			{
				return this._FECHA_COMPRA;
			}
			set
			{
				if ((this._FECHA_COMPRA != value))
				{
					this._FECHA_COMPRA = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_ESTADO_SOLICITUD_AMISTADResult
	{
		
		private int _SOLICITUD_ID;
		
		private string _ESTADO;
		
		private System.DateTime _FECHA_SOLICITUD;
		
		public SP_OBTENER_ESTADO_SOLICITUD_AMISTADResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLICITUD_ID", DbType="Int NOT NULL")]
		public int SOLICITUD_ID
		{
			get
			{
				return this._SOLICITUD_ID;
			}
			set
			{
				if ((this._SOLICITUD_ID != value))
				{
					this._SOLICITUD_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_SOLICITUD", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_SOLICITUD
		{
			get
			{
				return this._FECHA_SOLICITUD;
			}
			set
			{
				if ((this._FECHA_SOLICITUD != value))
				{
					this._FECHA_SOLICITUD = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_ITEMS_TIENDAResult
	{
		
		private int _OBJETO_ID;
		
		private string _NOMBRE_OBJETO;
		
		private int _PRECIO_PUNTOS;
		
		private string _DESCRIPCION;
		
		public SP_OBTENER_ITEMS_TIENDAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBJETO_ID", DbType="Int NOT NULL")]
		public int OBJETO_ID
		{
			get
			{
				return this._OBJETO_ID;
			}
			set
			{
				if ((this._OBJETO_ID != value))
				{
					this._OBJETO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_OBJETO", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NOMBRE_OBJETO
		{
			get
			{
				return this._NOMBRE_OBJETO;
			}
			set
			{
				if ((this._NOMBRE_OBJETO != value))
				{
					this._NOMBRE_OBJETO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO_PUNTOS", DbType="Int NOT NULL")]
		public int PRECIO_PUNTOS
		{
			get
			{
				return this._PRECIO_PUNTOS;
			}
			set
			{
				if ((this._PRECIO_PUNTOS != value))
				{
					this._PRECIO_PUNTOS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="NVarChar(255)")]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_JUEGOSResult
	{
		
		private int _JUEGO_ID;
		
		private string _NOMBRE_JUEGO;
		
		private string _TIPO_JUEGO;
		
		public SP_OBTENER_JUEGOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JUEGO_ID", DbType="Int NOT NULL")]
		public int JUEGO_ID
		{
			get
			{
				return this._JUEGO_ID;
			}
			set
			{
				if ((this._JUEGO_ID != value))
				{
					this._JUEGO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_JUEGO", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NOMBRE_JUEGO
		{
			get
			{
				return this._NOMBRE_JUEGO;
			}
			set
			{
				if ((this._NOMBRE_JUEGO != value))
				{
					this._NOMBRE_JUEGO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_JUEGO", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TIPO_JUEGO
		{
			get
			{
				return this._TIPO_JUEGO;
			}
			set
			{
				if ((this._TIPO_JUEGO != value))
				{
					this._TIPO_JUEGO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_LOGROS_BLOQUEADOSResult
	{
		
		private int _LOGRO_ID;
		
		private string _DESCRIPCION;
		
		private int _JUEGO_ID;
		
		private string _CRITERIO_DESBLOQUEO;
		
		private int _VALOR_CRITERIO;
		
		public SP_OBTENER_LOGROS_BLOQUEADOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOGRO_ID", DbType="Int NOT NULL")]
		public int LOGRO_ID
		{
			get
			{
				return this._LOGRO_ID;
			}
			set
			{
				if ((this._LOGRO_ID != value))
				{
					this._LOGRO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JUEGO_ID", DbType="Int NOT NULL")]
		public int JUEGO_ID
		{
			get
			{
				return this._JUEGO_ID;
			}
			set
			{
				if ((this._JUEGO_ID != value))
				{
					this._JUEGO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRITERIO_DESBLOQUEO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CRITERIO_DESBLOQUEO
		{
			get
			{
				return this._CRITERIO_DESBLOQUEO;
			}
			set
			{
				if ((this._CRITERIO_DESBLOQUEO != value))
				{
					this._CRITERIO_DESBLOQUEO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_CRITERIO", DbType="Int NOT NULL")]
		public int VALOR_CRITERIO
		{
			get
			{
				return this._VALOR_CRITERIO;
			}
			set
			{
				if ((this._VALOR_CRITERIO != value))
				{
					this._VALOR_CRITERIO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_LOGROS_DESBLOQUEADOSResult
	{
		
		private int _LOGRO_ID;
		
		private string _DESCRIPCION;
		
		private int _JUEGO_ID;
		
		private System.DateTime _FECHA_LOGRO;
		
		public SP_OBTENER_LOGROS_DESBLOQUEADOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOGRO_ID", DbType="Int NOT NULL")]
		public int LOGRO_ID
		{
			get
			{
				return this._LOGRO_ID;
			}
			set
			{
				if ((this._LOGRO_ID != value))
				{
					this._LOGRO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JUEGO_ID", DbType="Int NOT NULL")]
		public int JUEGO_ID
		{
			get
			{
				return this._JUEGO_ID;
			}
			set
			{
				if ((this._JUEGO_ID != value))
				{
					this._JUEGO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_LOGRO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_LOGRO
		{
			get
			{
				return this._FECHA_LOGRO;
			}
			set
			{
				if ((this._FECHA_LOGRO != value))
				{
					this._FECHA_LOGRO = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_NOTIFICACIONES_USUARIOResult
	{
		
		private string _TIPO_NOTIFICACION;
		
		private string _MENSAJE;
		
		private System.DateTime _FECHA_NOTIFICACION;
		
		public SP_OBTENER_NOTIFICACIONES_USUARIOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO_NOTIFICACION", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string TIPO_NOTIFICACION
		{
			get
			{
				return this._TIPO_NOTIFICACION;
			}
			set
			{
				if ((this._TIPO_NOTIFICACION != value))
				{
					this._TIPO_NOTIFICACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENSAJE", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string MENSAJE
		{
			get
			{
				return this._MENSAJE;
			}
			set
			{
				if ((this._MENSAJE != value))
				{
					this._MENSAJE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_NOTIFICACION", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_NOTIFICACION
		{
			get
			{
				return this._FECHA_NOTIFICACION;
			}
			set
			{
				if ((this._FECHA_NOTIFICACION != value))
				{
					this._FECHA_NOTIFICACION = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_PUNTAJE_TOTAL_USUARIOSResult
	{
		
		private int _USUARIO_ID;
		
		private int _PUNTAJE_TOTAL;
		
		private System.DateTime _FECHA_ACTUALIZACION;
		
		public SP_OBTENER_PUNTAJE_TOTAL_USUARIOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_ID", DbType="Int NOT NULL")]
		public int USUARIO_ID
		{
			get
			{
				return this._USUARIO_ID;
			}
			set
			{
				if ((this._USUARIO_ID != value))
				{
					this._USUARIO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PUNTAJE_TOTAL", DbType="Int NOT NULL")]
		public int PUNTAJE_TOTAL
		{
			get
			{
				return this._PUNTAJE_TOTAL;
			}
			set
			{
				if ((this._PUNTAJE_TOTAL != value))
				{
					this._PUNTAJE_TOTAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_ACTUALIZACION", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_ACTUALIZACION
		{
			get
			{
				return this._FECHA_ACTUALIZACION;
			}
			set
			{
				if ((this._FECHA_ACTUALIZACION != value))
				{
					this._FECHA_ACTUALIZACION = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_SANCIONESResult
	{
		
		private string _MENSAJE;
		
		public SP_OBTENER_SANCIONESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENSAJE", DbType="VarChar(48) NOT NULL", CanBeNull=false)]
		public string MENSAJE
		{
			get
			{
				return this._MENSAJE;
			}
			set
			{
				if ((this._MENSAJE != value))
				{
					this._MENSAJE = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_SOLICITUDES_AMISTAD_PENDIENTESResult
	{
		
		private int _SOLICITUD_ID;
		
		private int _USUARIO_EMISOR_ID;
		
		private string _NOMBRE_EMISOR;
		
		private string _ESTADO;
		
		private System.DateTime _FECHA_SOLICITUD;
		
		public SP_OBTENER_SOLICITUDES_AMISTAD_PENDIENTESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLICITUD_ID", DbType="Int NOT NULL")]
		public int SOLICITUD_ID
		{
			get
			{
				return this._SOLICITUD_ID;
			}
			set
			{
				if ((this._SOLICITUD_ID != value))
				{
					this._SOLICITUD_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_EMISOR_ID", DbType="Int NOT NULL")]
		public int USUARIO_EMISOR_ID
		{
			get
			{
				return this._USUARIO_EMISOR_ID;
			}
			set
			{
				if ((this._USUARIO_EMISOR_ID != value))
				{
					this._USUARIO_EMISOR_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_EMISOR", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOMBRE_EMISOR
		{
			get
			{
				return this._NOMBRE_EMISOR;
			}
			set
			{
				if ((this._NOMBRE_EMISOR != value))
				{
					this._NOMBRE_EMISOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_SOLICITUD", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_SOLICITUD
		{
			get
			{
				return this._FECHA_SOLICITUD;
			}
			set
			{
				if ((this._FECHA_SOLICITUD != value))
				{
					this._FECHA_SOLICITUD = value;
				}
			}
		}
	}
	
	public partial class SP_OBTENER_TODOS_LOS_REPORTESResult
	{
		
		private int _REPORTE_ID;
		
		private int _USUARIO_REPORTADO;
		
		private int _USUARIO_REPORTADOR;
		
		private string _DESCRIPCION;
		
		private System.DateTime _FECHA_REPORTE;
		
		private string _ESTADO;
		
		public SP_OBTENER_TODOS_LOS_REPORTESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REPORTE_ID", DbType="Int NOT NULL")]
		public int REPORTE_ID
		{
			get
			{
				return this._REPORTE_ID;
			}
			set
			{
				if ((this._REPORTE_ID != value))
				{
					this._REPORTE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_REPORTADO", DbType="Int NOT NULL")]
		public int USUARIO_REPORTADO
		{
			get
			{
				return this._USUARIO_REPORTADO;
			}
			set
			{
				if ((this._USUARIO_REPORTADO != value))
				{
					this._USUARIO_REPORTADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_REPORTADOR", DbType="Int NOT NULL")]
		public int USUARIO_REPORTADOR
		{
			get
			{
				return this._USUARIO_REPORTADOR;
			}
			set
			{
				if ((this._USUARIO_REPORTADOR != value))
				{
					this._USUARIO_REPORTADOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_REPORTE", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_REPORTE
		{
			get
			{
				return this._FECHA_REPORTE;
			}
			set
			{
				if ((this._FECHA_REPORTE != value))
				{
					this._FECHA_REPORTE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this._ESTADO = value;
				}
			}
		}
	}
	
	public partial class SP_RECUPERAR_MENSAJESResult
	{
		
		private int _MENSAJE_ID;
		
		private int _EMISOR_ID;
		
		private int _RECEPTOR_ID;
		
		private string _MENSAJE_TEXTO;
		
		private System.DateTime _FECHA_ENVIO;
		
		public SP_RECUPERAR_MENSAJESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENSAJE_ID", DbType="Int NOT NULL")]
		public int MENSAJE_ID
		{
			get
			{
				return this._MENSAJE_ID;
			}
			set
			{
				if ((this._MENSAJE_ID != value))
				{
					this._MENSAJE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMISOR_ID", DbType="Int NOT NULL")]
		public int EMISOR_ID
		{
			get
			{
				return this._EMISOR_ID;
			}
			set
			{
				if ((this._EMISOR_ID != value))
				{
					this._EMISOR_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RECEPTOR_ID", DbType="Int NOT NULL")]
		public int RECEPTOR_ID
		{
			get
			{
				return this._RECEPTOR_ID;
			}
			set
			{
				if ((this._RECEPTOR_ID != value))
				{
					this._RECEPTOR_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENSAJE_TEXTO", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string MENSAJE_TEXTO
		{
			get
			{
				return this._MENSAJE_TEXTO;
			}
			set
			{
				if ((this._MENSAJE_TEXTO != value))
				{
					this._MENSAJE_TEXTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_ENVIO", DbType="DateTime NOT NULL")]
		public System.DateTime FECHA_ENVIO
		{
			get
			{
				return this._FECHA_ENVIO;
			}
			set
			{
				if ((this._FECHA_ENVIO != value))
				{
					this._FECHA_ENVIO = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
